### ISSUE TITLE
Please check the free() or other scripts related with memory

### ISSUE THREAD

**Issue by starsareintherose** [bredelings/BAli-Phy#15]
OS: ArchLinux
Installation: https://github.com/BioArchLinux/Packages/blob/master/BioArchLinux/bali-phy/PKGBUILD

When I finished running this problem and then It is still running in the background and quickly fills up the CPU. I don't want to repeat it, but it's still a problem for other users.

**Comment by bredelings** [comment]
Thanks for the bug report.  Can you please give more information?

Do you mean it fills up the RAM, or the CPU?

After compilation, the installation process should run tests that take up the CPU.  That is not a bug.

**Comment by starsareintherose** [comment]
sorry, RAM, not compiling process, but after using it and it finished running. It starts to take up the RAM

**Comment by bredelings** [comment]
Hmm... what do you see if you run the `top` command in the terminal?  That gives more information than the 'runcat' command.

Also, what kind of input are you giving to bali-phy?  How many sequences?  How long are the sequences?

**Comment by starsareintherose** [comment]
very short sequence, just 3 samples CO1 section. and it has been finished. I don't want to repeat it, it will make my PC broken

**Comment by bredelings** [comment]
Can you send me the data set so I can test it?

**Comment by starsareintherose** [comment]
okay, no problem.

**Comment by bredelings** [comment]
I ran your example, and I'm not seeing a problem, either with memory usage or with CPU usage.

Note that a program cannot break your computer by using 100% CPU.  If you have two programs that try to use the CPU, they will share it.

What command line did you use?

How do you know that the analysis is finished?

**Comment by starsareintherose** [comment]
This program make CPU occupy to 100% shown by the gnome extension
I will report it when I would like to repeat it.
