### ISSUE TITLE
<bitset> needs inclusion in src/dp/hmm.cc

### ISSUE THREAD

**Issue by joelb123** [bredelings/BAli-Phy#16]
BAli-Phy 3.6.1
gcc 12.2.1
glibc 2.36

Compilation error, bitset undefined. Fixed by this:

`diff --git a/src/dp/hmm.cc b/src/dp/hmm.cc
index 8be51b5..ea8a15e 100644
--- a/src/dp/hmm.cc
+++ b/src/dp/hmm.cc
@@ -24,6 +24,7 @@
 ///
 
 #include <cmath>
+#include <bitset>
 #include "hmm.H"
 #include "2way.H"
 #include "imodel/imodel.H"
`

**Comment by bredelings** [comment]
Hi Joel,

Is this still an issue with the git master branch?

-BenRI

**Comment by joelb123** [comment]
I haven't tried it against master.
