### ISSUE TITLE
Test suite error in 4.0-beta7

### ISSUE THREAD

**Issue by tillea** [bredelings/BAli-Phy#17]
Hi,
I tried to package 4.0-beta7 for Debian.  In our CI you can find a [full build log](https://salsa.debian.org/med-team/bali-phy/-/jobs/5056307#L1175) which contains an error in one test:

    5/37 bali-phy 5d -A 200             FAIL             10.83s   killed by signal 11 SIGSEGV
    >>> ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 MALLOC_PERTURB_=129 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 /builds/med-team/bali-phy/debian/output/source_dir/obj-x86_64-linux-gnu/src/bali-phy/bali-phy /builds/med-team/bali-phy/debian/output/source_dir/obj-x86_64-linux-gnu/../examples/5S-rRNA/5d.fasta --iter=200 --package-path=/builds/med-team/bali-phy/debian/output/source_dir/obj-x86_64-linux-gnu/src/builtins:/builds/med-team/bali-phy/debian/output/source_dir -Inone

Please let me know if you need further information.
Kind regards, Andreas.

**Comment by bredelings** [comment]
Hi Andreas,

Thanks! I am traveling overseas right now and my internet access is limited, so I might not be able to fully investigate this until I get back on Dec 31.

I'm not quite sure why that test would crash.  The current development version doesn't seem to crash when I enable the address sanitizer, so I tagged it 4.0-beta8.  Does that work?

-BenRI

**Comment by tillea** [comment]
Hi Ben,
have a nice travel - but I do not have good news for you.  The tagged 4.0-beta8 [fails as well](https://salsa.debian.org/med-team/bali-phy/-/jobs/5059851#L1204).  I'm not in a hurry - just wanted to report this before you might tag the final release.
Kind regards, Andreas.

**Comment by bredelings** [comment]
I was able to reproduce the bug and figure out where it is coming from.

**Comment by bredelings** [comment]
I've fixed the testsuite error on the `master` branch.  I'm planning to do a new beta9 release at the end of January, which would include the fix.  I'm aiming to do the 4.0 release around Jun.

**Comment by bredelings** [comment]
Hi Andreas,
I finally did a beta9 release, so the issue should be fixed.  Would you be able to build beta9 for experimental?
-BenRI

**Comment by bredelings** [comment]
Hi Andreas,
Would you be able to build beta13 for experimental?
-BenRI

**Comment by emollier** [comment]
Hi Benjamin,

I confirm the [issue is resolved on Debian end] too with beta13.  Thanks!

Have a nice day,  :)
Étienne.

[issue is resolved on Debian end]: https://salsa.debian.org/med-team/bali-phy/-/jobs/5786155

**Comment by emollier** [comment]
I forgot to mention the package is upload to Debian experimental for further tests.
