### ISSUE TITLE
Builds are not available from website

### ISSUE THREAD

**Issue by mathiasbockwoldt** [bredelings/BAli-Phy#2]
The current (stable) releases are not available from the website (e.g. <http://bali-phy.org/files/bali-phy-2.3.8-linux64.tar.gz> but also the versions for OSX and Windows).

**Comment by bredelings** [comment]
Thanks Matthias!  I didn't realize that.  Should be fixed now.

**Comment by bredelings** [comment]
Moved some of the files into /files/ directory.  The old ones are still at http://bali-phy.org/bali-phy-<version>.tar.gz
